import 'package:flutter/foundation.dart';
import 'logs_models.dart';
import 'logs_repository.dart';

class LogService {
  final LogsRepository _repository;

  LogService(this._repository);

  /// Helper to post a log entry
  Future<void> log({
    required LogLevel level,
    required LogModule module,
    required LogCategory category,
    required String message,
    String? sourceFile,
    String? destinationFile,
    int? durationMs,
    String? workerId,
    int? fileSize,
    String? sha256,
    String? status,
    String? errorCode,
    String? exceptionDetails,
    bool isImportant = false,
  }) async {
    final entry = LogEntry(
      id: 0, // Generated by database
      timestamp: DateTime.now(),
      level: level,
      module: module,
      category: category,
      message: message,
      sourceFile: sourceFile,
      destinationFile: destinationFile,
      durationMs: durationMs,
      workerId: workerId,
      fileSize: fileSize,
      sha256: sha256,
      status: status,
      errorCode: errorCode,
      exceptionDetails: exceptionDetails,
      isImportant: isImportant || level == LogLevel.error,
    );

    try {
      await _repository.addLogEntry(entry);
    } catch (e) {
      debugPrint('Error writing structured log: $e');
    }
  }

  // --- Category Specific API Helper Methods ---

  Future<void> backupStarted({
    required String workerId,
    required String sourcePath,
  }) async {
    await log(
      level: LogLevel.info,
      module: LogModule.backup,
      category: LogCategory.backupStarted,
      message: 'Backup process started for worker $workerId',
      sourceFile: sourcePath,
      workerId: workerId,
    );
  }

  Future<void> backupCompleted({
    required String workerId,
    required String sourcePath,
    required String destPath,
    required int fileSize,
    required int durationMs,
    String? sha256,
  }) async {
    await log(
      level: LogLevel.success,
      module: LogModule.backup,
      category: LogCategory.backupCompleted,
      message: 'Backup process completed successfully for worker $workerId',
      sourceFile: sourcePath,
      destinationFile: destPath,
      fileSize: fileSize,
      durationMs: durationMs,
      workerId: workerId,
      sha256: sha256,
      status: 'success',
    );
  }

  Future<void> backupFailed({
    required String workerId,
    required String sourcePath,
    required String errorMsg,
    String? errorCode,
    String? stackTrace,
  }) async {
    await log(
      level: LogLevel.error,
      module: LogModule.backup,
      category: LogCategory.backupFailed,
      message: 'Backup process failed: $errorMsg',
      sourceFile: sourcePath,
      workerId: workerId,
      errorCode: errorCode,
      exceptionDetails: stackTrace,
      status: 'failed',
    );
  }

  Future<void> restoreStarted({
    required String workerId,
    required String destPath,
  }) async {
    await log(
      level: LogLevel.info,
      module: LogModule.restore,
      category: LogCategory.restoreStarted,
      message: 'Restore process started for worker $workerId',
      destinationFile: destPath,
      workerId: workerId,
    );
  }

  Future<void> restoreCompleted({
    required String workerId,
    required String sourcePath,
    required String destPath,
    required int durationMs,
  }) async {
    await log(
      level: LogLevel.success,
      module: LogModule.restore,
      category: LogCategory.restoreCompleted,
      message: 'Restore process completed successfully for worker $workerId',
      sourceFile: sourcePath,
      destinationFile: destPath,
      durationMs: durationMs,
      workerId: workerId,
      status: 'success',
    );
  }

  Future<void> restoreFailed({
    required String workerId,
    required String destPath,
    required String errorMsg,
    String? errorCode,
    String? stackTrace,
  }) async {
    await log(
      level: LogLevel.error,
      module: LogModule.restore,
      category: LogCategory.restoreFailed,
      message: 'Restore process failed: $errorMsg',
      destinationFile: destPath,
      workerId: workerId,
      errorCode: errorCode,
      exceptionDetails: stackTrace,
      status: 'failed',
    );
  }

  Future<void> folderAdded(String path) async {
    await log(
      level: LogLevel.success,
      module: LogModule.folderManager,
      category: LogCategory.folderAdded,
      message: 'New folder added for monitoring: $path',
      sourceFile: path,
    );
  }

  Future<void> folderRemoved(String path) async {
    await log(
      level: LogLevel.warning,
      module: LogModule.folderManager,
      category: LogCategory.folderRemoved,
      message: 'Folder removed from monitoring: $path',
      sourceFile: path,
    );
  }

  Future<void> folderModified(String path, String changes) async {
    await log(
      level: LogLevel.info,
      module: LogModule.folderManager,
      category: LogCategory.folderModified,
      message: 'Folder configuration modified for $path: $changes',
      sourceFile: path,
    );
  }

  Future<void> watcherStarted(String path) async {
    await log(
      level: LogLevel.info,
      module: LogModule.watcher,
      category: LogCategory.watcherStarted,
      message: 'File watcher active for path: $path',
      sourceFile: path,
    );
  }

  Future<void> watcherStopped(String path) async {
    await log(
      level: LogLevel.info,
      module: LogModule.watcher,
      category: LogCategory.watcherStopped,
      message: 'File watcher stopped for path: $path',
      sourceFile: path,
    );
  }

  Future<void> workerStarted(String workerId) async {
    await log(
      level: LogLevel.debug,
      module: LogModule.system,
      category: LogCategory.workerStarted,
      message: 'Worker thread $workerId instantiated',
      workerId: workerId,
    );
  }

  Future<void> workerStopped(String workerId) async {
    await log(
      level: LogLevel.debug,
      module: LogModule.system,
      category: LogCategory.workerStopped,
      message: 'Worker thread $workerId stopped',
      workerId: workerId,
    );
  }

  Future<void> settingsChanged(String section, String detail) async {
    await log(
      level: LogLevel.warning,
      module: LogModule.settings,
      category: LogCategory.settingsChanged,
      message: 'Settings updated in $section: $detail',
    );
  }

  Future<void> startup() async {
    await log(
      level: LogLevel.system,
      module: LogModule.system,
      category: LogCategory.startup,
      message: 'BackupVault Engine Started',
      isImportant: true,
    );
  }

  Future<void> shutdown() async {
    await log(
      level: LogLevel.system,
      module: LogModule.system,
      category: LogCategory.shutdown,
      message: 'BackupVault Engine Clean Shutdown Executed',
      isImportant: true,
    );
  }

  Future<void> crash(String errorMessage, String stackTrace) async {
    await log(
      level: LogLevel.error,
      module: LogModule.system,
      category: LogCategory.crash,
      message: 'Fatal Engine Crash: $errorMessage',
      exceptionDetails: stackTrace,
      isImportant: true,
    );
  }

  Future<void> warning(String moduleName, String message) async {
    await log(
      level: LogLevel.warning,
      module: LogModule.fromString(moduleName),
      category: LogCategory.warning,
      message: message,
    );
  }

  Future<void> info(String moduleName, String message) async {
    await log(
      level: LogLevel.info,
      module: LogModule.fromString(moduleName),
      category: LogCategory.information,
      message: message,
    );
  }

  Future<void> debug(String moduleName, String message) async {
    await log(
      level: LogLevel.debug,
      module: LogModule.fromString(moduleName),
      category: LogCategory.debug,
      message: message,
    );
  }

  Future<void> systemEvent(String message) async {
    await log(
      level: LogLevel.system,
      module: LogModule.system,
      category: LogCategory.systemEvents,
      message: message,
    );
  }
}
